name: Rust

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustc --version && cargo --version
    - run: cargo fmt --check
    - run: cargo clippy --all-targets -- --deny warnings
    - run: cargo test --verbose
